### PR TITLE
remove nc_complex submodule, add source files directly

### PR DESCRIPTION
**Pull request by jswhit**
the following files from [nc_complex](https://github.com/PlasmaFAIR/nc-complex/releases/tag/v0.2.0) are added
```
external/nc_complex/src/nc_complex.c
external/nc_complex/include/nc_complex/nc_complex.h
external/nc_complex/include/generated_fallbacks/nc_complex_version.h
````

see issues #1329, #1331 and #1332

### CODE REVIEW

**Comment by aaraney** [comment]
Linking relevant conversation in #1332 here. https://github.com/Unidata/netcdf4-python/pull/1332#issuecomment-2170016234 

I really don't think it's a good idea to vendor in this way without some sort of upstream synchronization and checked in vendored version provenance information.

**Comment by jswhit** [comment]
I've included a README with provenance info (the source files come from https://github.com/PlasmaFAIR/nc-complex/releases/tag/v0.2.0)

**Comment by ZedThree** [comment]
@jswhit Apologies, I've been on holiday the last couple of weeks so I missed all the fun with the submodules!

If vendoring `nc-complex` simplifies things, then it's probably the most sensible way forward, it just complicates updating it slightly -- although I'm not expecting a great deal of future updates.

I would say though, that it would be best to include a generated `nc_complex_version.h` with the exact commit hash used. You've noted the version in the `README`, but including the hash would be even better.

One option for the future would be to move the build system to [scikit-build](https://scikit-build-core.readthedocs.io/en/latest/) and make sure the submodules are initialised. Probably a github action could be used to uploaded a full tarball on releases too.

**Comment by aaraney** [comment]
@ZedThree, yeah you could take inspiration from [`pytorch`](https://github.com/pytorch/pytorch/blob/f0d68120f4e99ee6c05f1235d9b42a4524af39d5/.github/workflows/create_release.yml).

**Comment by ZedThree** [comment]
@aaraney Thanks, I know a couple of other projects that could use that too!

**Comment by jswhit** [comment]
> @jswhit Apologies, I've been on holiday the last couple of weeks so I missed all the fun with the submodules!
> 
> If vendoring `nc-complex` simplifies things, then it's probably the most sensible way forward, it just complicates updating it slightly -- although I'm not expecting a great deal of future updates.
> 
> I would say though, that it would be best to include a generated `nc_complex_version.h` with the exact commit hash used. You've noted the version in the `README`, but including the hash would be even better.
> 
> One option for the future would be to move the build system to [scikit-build](https://scikit-build-core.readthedocs.io/en/latest/) and make sure the submodules are initialised. Probably a github action could be used to uploaded a full tarball on releases too.

@ZedThree how is `nc_complex_version.h` generated? I used the one from v0.2.0 tag, but it says version 0.1.0 in it.

**Comment by jswhit** [comment]
> > @jswhit Apologies, I've been on holiday the last couple of weeks so I missed all the fun with the submodules!
> > If vendoring `nc-complex` simplifies things, then it's probably the most sensible way forward, it just complicates updating it slightly -- although I'm not expecting a great deal of future updates.
> > I would say though, that it would be best to include a generated `nc_complex_version.h` with the exact commit hash used. You've noted the version in the `README`, but including the hash would be even better.
> > One option for the future would be to move the build system to [scikit-build](https://scikit-build-core.readthedocs.io/en/latest/) and make sure the submodules are initialised. Probably a github action could be used to uploaded a full tarball on releases too.
> 
> @ZedThree how is `nc_complex_version.h` generated? I used the one from v0.2.0 tag, but it says version 0.1.0 in it.

NVM I figured it out - it gets created by the cmake build.

**Pull request merged**
