### PR TITLE
fixes #686 Encode filename with sys.getfilesystemencoding()

### LINKED ISSUE #686: filename is encoded to utf8, resulting in broken filenames on windows
When i try to create a netcdf-file with a filepath, that contains Non-ASCII-characters, Netcdf4 creates broken filenames on windows, because it encodes the filepath in UTF8, which is fine for Linux,. In Windows, the filepath has to be convertet to CP1252.

```python
import netCDF4 as nc4
filepath = r'C:\Plön.nc'
ds = nc4.Dataset(filepath, 'w')
ds.close()
```

this creates a file 
PlÃ¶n.nc

I could try to avoid Non-ASCII-Characters in .nc filenames, but if i want to create a file in the folder
C:\Plön\
```python
import netCDF4 as nc4
filepath = r'C:\Plön\Ploen.nc'
ds = nc4.Dataset(filepath, 'w')
ds.close()
```
then i get the confusing error message:
builtins.OSError: Permission denied
Because the folder "Plön" is not recognized correctly.

The solution would be to pass the filesystemencoding to _strencode in 
_netCDF4.pyx in line 1796
```diff
-  bytestr = _strencode(str(filename))
+ bytestr = _strencode(str(filename), encoding=sys.getfilesystemencoding())
```
I'll create a pull request.
Max

### PR DESCRIPTION
**Pull request by MaxBo**
fixes file encoding and decodes the filepath from the default filesystemencoding - or form percentage-encoding if it is a OpenDAV Datasource

### CODE REVIEW

**Comment by MaxBo** [comment]
Test test_filepath in appveyor failed, but checks have passed. Don't merge yet.
```
(C:\Miniconda-x64\conda-bld\netcdf4_1499351439744\_t_env) (root) C:\Miniconda-x64\conda-bld\netcdf4_1499351439744\test_tmp>"C:\Miniconda-x64\conda-bld\netcdf4_1499351439744\_t_env\python.exe" -s "C:\Miniconda-x64\conda-bld\netcdf4_1499351439744\test_tmp\run_test.py" 
..............F...............................................................................not running tst_unicode3.py ...
not running tst_dap.py ...
netcdf4-python version: 1.3.0
HDF5 lib version:       1.8.17
netcdf lib version:     4.4.1.1
numpy version           1.11.3
======================================================================
FAIL: test_filepath_with_non_ascii_characters (tst_filepath.test_filepath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\conda-bld\netcdf4_1499351439744\test_tmp\test\tst_filepath.py", line 24, in test_filepath_with_non_ascii_characters
    assert nc_non_ascii.filepath() == str(nc_non_ascii_file)
AssertionError
----------------------------------------------------------------------
Ran 94 tests in 33.469s
FAILED (failures=1)
```

**Comment by jswhit** [comment]
typo in _netCDF4.pyx is causing compilation to fail.

**Comment by MaxBo** [comment]
Sorry, Fixed. 
Using explicit distinction for the encoding between windows and linux/os now, because sys.getfilesystemencoding() returns 'utf-8' on the Appveyor-testsystem, which makes the test fail - maybe because it's a virtual machine.
Unittests pass now on Appveyor for python 2 and 3. 
On Travis, test_filepath is still skipped.

**Comment by jswhit** [comment]
Can you explain what you are doing with this patch?  It appears that you assume that the filepath is always encoded as 'mbcs' on windows and 'utf8' on everything else.  

I found some discussion windows filename encoding in python here

https://www.python.org/dev/peps/pep-0529/#use-strict-mbcs-decoding

It was ultimately decided to use utf-8 and not mbcs.

**Comment by jswhit** [comment]
Maybe a more general solution would be to provide an optional `encoding` kwarg to `Dataset.__init__` and `Dataset.filepath`, with the default set to `utf-8`.  Then we wouldn't have to make choices based on platform.

**Comment by MaxBo** [comment]
Dear Jeff,

thanks for adding the kwargs-encoding parameter. This should work for me.

I assumed that windows filepaths are encoded as 'mbcs', because on my local windows machine, sys.getfilesystemencoding() returns mbcs. On the he AppVeyor-Test-Environment sys.getfilesystemencoding() returned utf8. 
In the test_filepath.py i used a filepath with a directoryname, that contained non-ascii-characters. 
```
tempdir = tempfile.mkdtemp(prefix=u'ÄÖÜß_')
```
When i encoded the filepath with utf8 (which sys.getfilesystemencoding() returned on Appveyor), the test failed with an OSError, because the tempdir was not found. When i used a hardcoded encoding='mbcs', the test passed. So i assumed that on windows the encoding was always mbcs, regardless what sys.getfilesystemencoding() returned.
I did not know the discussion in
https://www.python.org/dev/peps/pep-0529/#use-strict-mbcs-decoding

So your solution with the kwargs-parameter should be fine.
I'll add onother test with a directory containing Non-Ascii-characters.
Thanks,

Max

**Comment by jswhit** [comment]
This is all very confusing.   Having an extra `encoding` kwarg argument seems the most flexible, and should in principle be able to deal with every situation.  However, it forces the user to know what the filename encoding is.  Your original solution sys.getfilesystemencoding() should work - it's just hard to create tests for systems with different default encodings that appveyor uses.  Also, it will fail for illegally encoded filenames (filenames will different encodings that the system default).  

So, I think we have three choices here:

1) use sys.getfilesystemencoding() to encode the filename in Dataset.__init__ and decode back into a string in Dataset.filepath.  No extra kwarg args added, keeps interface simpler - but may fail in some cases.

2) use an encoding specified as a kwarg argument in Dataset.__init__ and Dataset.filepath.  Forces user to know what the filename encoding is.

or 

3) as in (2), but use sys.getfilesystemencoding()  if no encoding kwarg is specified.

I've updated the pull request to use option (3).

**Comment by MaxBo** [comment]
Thanks a lot - i think this should work now.

**Pull request closed without merging**
