### PR TITLE
Support for pnetcdf

### PR DESCRIPTION
**Pull request by pastewka**
Added support for parallel writing of NetCDF3 files through the PNetCDF library. Bindings now autodetect if netcdf4 has been compiled with parallel HDF5 and/or pnetcdf support and enables parallel output accordingly.

### CODE REVIEW

**Comment by jswhit2** [comment]
This is really great - thank you!  If no one has any comments by Friday I will go ahead and merge.

**Comment by jswhit2** [comment]
Could you please add a Changelog entry?

**Comment by pastewka** [comment]
Just added the changelog entry

**Comment by jswhit** [comment]
Merging now. This is an important enough addition that I think we should make a new release (1.5.0). I'll try to do that next week.  Thanks @pastewka !

**Comment by pastewka** [comment]
Perfect, thanks for merging it this quickly!

________________________________
Von: Jeff Whitaker <notifications@github.com>
Gesendet: Freitag, 22. März 2019 13:43
An: Unidata/netcdf4-python
Cc: Lars Pastewka; Mention
Betreff: Re: [Unidata/netcdf4-python] Support for pnetcdf (#897) 

Merging now. This is an important enough addition that I think we should make a new release (1.5.0). I'll try to do that next week. Thanks @pastewka !

**Pull request merged**
