### PR TITLE
covert scripts to entry_points

### PR DESCRIPTION
**Pull request by mindw**
windows friendly scripts.

### CODE REVIEW

**Comment by jswhit** [comment]
I'm not familiar with 'entry points' in setuptools.  Can you explain why this makes the scripts 'windows friendly'?

**Comment by mindw** [comment]
... On Windows, a set of foo.exe, bar.exe, and baz.exe launchers are created, alongside a set of foo.py, bar.py, and baz.pyw files. The .exe wrappers find and execute the right version of Python to run the .py or .pyw file ...

https://packaging.python.org/en/latest/distributing.html#console-scripts
https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation

**Comment by jswhit** [comment]
Seems reasonable - but it does require setuptools, which is not currently required to build netcdf4-python.

**Comment by mindw** [comment]
https://packaging.python.org/en/latest/current.html#id6


Even for projects that do choose to use distutils, when *pip*
<https://packaging.python.org/en/latest/projects.html#pip> installs such
projects directly from source (rather than installing from a prebuilt
*wheel* <https://packaging.python.org/en/latest/glossary.html#term-wheel>
file),
it will actually build your project using *setuptools*
<https://packaging.python.org/en/latest/projects.html#setuptools> instead.


-gabi

**Comment by mindw** [comment]
In any case - the latest version is distutils friendly

**Comment by jswhit** [comment]
OK, great.  Merging now - thanks for the contribution.

**Pull request merged**
