### PR TITLE
switch to trusty to get netcdf 4.3

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Comment by ckhroulev** [comment]
I think it is helpful to have an automatic test (in Travis CI or similar) that uses the oldest supported NetCDF version (currently 4.1.1, if I'm not mistaken).

What's your take on this?

**Comment by jswhit** [comment]
Yes, I agree in principle, but I also think 4.1.1 is too old to bother with.

**Comment by ckhroulev** [comment]
Agreed.

What should the "oldest supported version" be then? Should we replace "4.1.1" with "4.x.y" in documentation? (After you pick x and y, that is.)

Also, @shoyer recently brought up dropping Python 2.6 support. What do you think about that?

**Comment by jswhit** [comment]
I agree with dropping python 2.6. I see that  netcdf-c 4.1.3 is the default version in trusty.

**Comment by jswhit** [comment]
I'd like to go ahead and commit this, since it is the right thing to do.  Let's just disable the test for right now until we figure out why it fails on Ubuntu.

**Pull request closed without merging**
