### PR TITLE
v1.2.8 release 

### PR DESCRIPTION
**Pull request by jswhit**
updates to README.md and Changelog

### CODE REVIEW

**Comment by matthew-brett** [comment]
I built wheels for this branch, available at:

https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com

Building repo, as usual at https://github.com/MacPython/netcdf4-python-wheels

If the code here will be the eventual release, then these wheels are good to go (they have names `netCDF4-1.2.8-cp*`).  Otherwise, they will need to be rebuilt when the code is finalized, before uploading.

**Comment by jswhit** [comment]
Great - thanks!  I don't anticipate any changes so those wheels should do fine.

**Comment by shoyer** [comment]
Is there something else you're waiting for on making netCDF4-Python depend on netcdftime, rather than bundling it?

**Comment by shoyer** [comment]
I guess the work on netcdftime mentioned in https://github.com/Unidata/netcdf4-python/issues/601 still needs to be finished. So please ignore me :).

**Comment by ocefpaf** [comment]
> I guess the work on netcdftime mentioned in #601 still needs to be finished. So please ignore me :).

It would be nice to get this in the next release. Maybe it is too late for 1.2.8 though.

@shoyer and @jhamman I can offer a few hours to help with https://github.com/Unidata/netcdf4-python/issues/601#issuecomment-259301491 (I'll start with testing and the boilerplate for the package release tomorrow.)

**Comment by jswhit** [comment]
I can release 1.2.9 (with netcdftime removed) as soon as you are ready.

**Pull request merged**
