### PR TITLE
don't release GIL in Dataset.__init__

### PR DESCRIPTION
**Pull request by jswhit**
potential fix for issue  #1192

### CODE REVIEW

**Comment by dopplershift** [comment]
Personally, I think it's a mistake for users to rely on the GIL to make netcdf "threadsafe".

**Comment by jswhit** [comment]
Understood @dopplershift. Perhaps the GIL may have been prevented some segfaults, but results still may have been incorrect.

**Comment by ocefpaf** [comment]
What is the advantage to maintain this part of the code and let users fix it instead vs merging this to safe guard bad use? My impression is that most folks opening issue don't even know they are abusing the GIL there.

**Comment by dopplershift** [comment]
Previously, the library was inconsistently releasing the GIL, as in: some methods were already releasing it and were thread unsafe. (I've personally encountered crashes as a result). So to truly solve the problem and eliminate all potential crashes due to Python-based multithreading, you'd need to not only revert #1181, but #370 as well, and make sure ALL calls hold the GIL.

Personally, I'd rather have the option for better performance for use cases that aren't trying to use multiple netCDF files, but doing other things concurrently in the interpreter. I do see that this change has been a bit disruptive, so I'm not going to fight for it. It's also not my library, so my opinion counts very little. :wink:

**Pull request closed without merging**
