### PR TITLE
prepare for 1.6.3 release

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Comment by jswhit** [comment]
@ocefpaf could you build windows wheels with [netcdf4-win-wheels](https://github.com/ocefpaf/netcdf4-win-wheels) using the v1.6.3rel release branch?  (either that, or add me as an owner to that project so I can do it).

**Comment by ocefpaf** [comment]
> @ocefpaf could you build windows wheels with [netcdf4-win-wheels](https://github.com/ocefpaf/netcdf4-win-wheels) using the v1.6.3rel release branch?


I started it in https://github.com/ocefpaf/netcdf4-win-wheels/pull/8

>  (either that, or add me as an owner to that project so I can do it).

Why not both ;-p

**Comment by ocefpaf** [comment]
PS: @jswhit you should have access to it already. Let me know if that is not true and I can try to fix it.

**Comment by jswhit** [comment]
OK, thanks @ocepaf!  I will issue the PR myself next time.

**Comment by ocefpaf** [comment]
> OK, thanks @ocepaf! I will issue the PR myself next time.

Feel free to ping me if you need anything. Also, I'd be happy to transfer this repo to unidata or you gh user if you want. Anything that makes it easier to publish the wheels.

**Pull request merged**
