### PR TITLE
new methods to optionally re-enable old numpy array type behaviour (issue #809)

### PR DESCRIPTION
**Pull request by davidhassell**

### CODE REVIEW

**Comment by jswhit** [comment]
Looks good, thanks @davidhassell

**Comment by akrherz** [comment]
Just a comment from the peanut gallery here and I know API design is hard, but the name `set_auto_array_type` does not seem intuitive to me.  This setting is controlling whether variables should always be numpy masked arrays or not.  Currently `set_auto_mask(self, True_or_False)` exists, it seems like a companion to this would be `set_always_mask(self, True_or_False)`  ?

Just my unqualified two cents here.

**Comment by davidhassell** [comment]
@jswhit, are you happy to rename the methods, as per @akrherz's suggestion?

**Comment by jswhit** [comment]
Not quite clear on what `set_always_mask` would do.  Would it be `True` but default, and to enable the old behavior it would be set to `False`?

**Comment by jswhit** [comment]
as per the discussion in issue #809, please go ahead and change
 
```python
            # issue #785: always return masked array, if no values masked
            # set mask=False.
            data = ma.masked_array(data,mask=False,fill_value=fill_value)
```

to 

```python
            # issue #785: always return masked array by default, if no values masked
            data = ma.masked_array(data,fill_value=fill_value)
```

**Comment by davidhassell** [comment]
Yes - The logic needs reversing when we rename to `set_auto_array_type` to `set_always_mask`. The default would be True, signifying that masked arrays are returned in every instance. I'll add this.

**Comment by jswhit** [comment]
Looks like tst_multifile.py is failing somewhere in cftime.  Restoring the 'mask=False' fixes it.

**Comment by davidhassell** [comment]
I suggest, then, that we restore `mask=False` here and revisit it in #808 (i.e. see if we can fix the downstream issues in cftime as pull request on that ticket (which I'm happy to look at, if you like)). I'll put `mask=False` back in this ticket's PR. Thanks

**Pull request merged**
