### PR TITLE
Add per Dataset encoding support

### PR DESCRIPTION
**Pull request by thehesiod**
- resolves https://github.com/Unidata/netcdf4-python/issues/654
- fixes warning related to `nc_open_mem` change
- bumps up cython to 0.20 for `basestring` support

### CODE REVIEW

**Comment by thehesiod** [comment]
btw to make it more backwards compatible we could instead change the default encoding to `None`, with a dynamic fallback in the `encoding.__get__`  lookup to `default_encoding` instead of fixing it during `__init__`.  thoughts?

**Comment by thehesiod** [comment]
hah, that recursion bug was a doozy, put a warning for future devs

**Comment by thehesiod** [comment]
cool, looks like this PR is ready for review!

**Comment by jswhit** [comment]
I'm waiting on this to see how the discussion on netcdf-c plays out (https://github.com/Unidata/netcdf-c/issues/402)

**Comment by jswhit** [comment]
What if different NC_STRING variables within the same dataset contain data with different encodings?  I suppose this could be handled with the proposed `_Encoding` attribute. 

The whole thing is a mess and any solution I can think of (including this one) seems fragile and kludgy.  At least we have a solution now that works as long as you know the encoding and you only are reading data from one Dataset at a time.

**Comment by thehesiod** [comment]
ya, we need per variable encoding fallbacks.  Let me know how you'd like to handle that.  Some ideas:
- user specified callback that takes one parameter (variable name) and returns encoding to use in case `_Encoding` not specified and it's a char type.
- a `Dataset.get_variable` method which you can use to specify and encoding

**Comment by jswhit** [comment]
Is your use case (for specifying an encoding) mainly for attributes, or variable data?

**Comment by thehesiod** [comment]
variable data, based on the conversations in the netcdf-c thread it sounds like attribute should all be forced to utf-8 (which I can change in this PR too).

**Comment by jswhit** [comment]
The reason I ask is if you are mainly concerned about attributes, we could add a kwarg `encoding` to getncattr.  You would then have to use getncattr to retrieve string attributes, but you could specify the encoding on a per attribute basis (no need for a Dataset encoding parameter).

**Comment by jswhit** [comment]
Could you post one of the MADIS files that you are dealing with?

**Comment by thehesiod** [comment]
https://madis-data.cprk.ncep.noaa.gov/madisPublic1/data/archive/2017/02/01/LDAD/mesonet/netCDF/20170201_0000.gz

**Comment by jswhit** [comment]
thanks @thehesiod.  I've created an alternate 'solution' in the 'encoding' branch.  Instead of setting the encoding as a Dataset init parameter, I look for an _Encoding attribute for character and vlen string variables.  For string variables, if _Encoding is not set, 'utf-8' is used.  For character arrays, if _Encoding is set, then a numpy array of fixed length strings is returned by automatically calling chartostring (the rightmost dimension of the variable is assumed to the the length of the strings).  If _Encoding is not set, you get the previous behavior (an array of single characters is returned).   So, in your case you would have to add `_Encoding="cp1252"` as a variable attribute, either using NCO or by opening the file in append mode and adding the attribute before you read the data.

For attributes, I added a 'encoding' kwarg to getncattr.

I know adding a new attribute to all the files is probably not a good solution for you, but I'm still a bit confused about what the problem is you are trying to solve.  With the current master, you can read the variable stationName and convert it to an array of strings using chartostring - but it will use the global module variable 'default_encoding'.  Wouldn't simply adding a kwarg 'encoding' to chartostring solve your problem?  (this is also done in the 'encoding' branch).

To be specific, here's what I'm suggesting:

```python
from netCDF4 import Dataset, chartostring
nc = Dataset('20170201_0000')
chararr = nc['stationName'][:]
strarr = chartostring(chararr,encoding='cp1252')
print strarr[77]
nc.close()
```

**Comment by thehesiod** [comment]
ya thinking about it more doesn't make sense to need an encoding init param for chat variable data, not sure why I thought I needed this.  Closing this PR

**Pull request closed without merging**
