### PR TITLE
Support reading and writing string array attributes. See #592.

### PR DESCRIPTION
**Pull request by ckhroulev**
This adds support for reading and writing string arrays.

``` python
import netCDF4
d = netCDF4.Dataset("foo.nc", "w")
d.char_attr = ["one", "string"] # no change in behavior: writes an NC_CHAR attribute, concatenating strings
d.setncattr_string("string_attr", ["two", "strings"]) # writes an NC_STRING attribute with 2 entries
d.close()
```

Results:

```
netcdf foo {

// global attributes:
        :char_attr = "onestring" ;
        string :string_attr = "two", "strings" ;
}
```

As a side effect

```
d.setncattr_string("string_attr", 1)
```

no longer writes the string `"1"` to the global attribute `"string_attr"`. (Calling `setncattr_string` with a value that is neither a string nor a sequence of strings should probably be an error.)

_Reading_ string array attributes is gives lists of strings.

### CODE REVIEW

**Comment by jswhit** [comment]
thanks for this @ckhroulev.  I will try this out this weekend.

**Comment by jswhit** [comment]
This looks great!  I think all it needs is a Changelog entry,  an update to the `setncattr_string` docstring, and a test.

**Comment by ckhroulev** [comment]
I can reproduce this test failure and will push a fix soon.

PS: It's strange that AppVeyor did not catch the failure (it did fail, though).

**Comment by jswhit** [comment]
minor typo in docstring:   "attirbute" should be "attribute".

**Comment by jswhit** [comment]
also, Travis tests are failing for Python 3

**Comment by ckhroulev** [comment]
@jswhit Yep. I'm working on it.

**Comment by jswhit** [comment]
great!  I'll wait a day or two and then merge.

**Comment by jswhit** [comment]
merging now...

**Pull request merged**
