### PR TITLE
version 1.2.5 release

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Comment by matthew-brett** [comment]
I'm seeing this test failure for the wheel builds:

```
.........................................................................syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: <!DOCTYPE^ html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> <link rel='stylesheet' href='/opendap/docs/css/contents.css' type='text/css'/> <title>Hyrax: ERROR</title> <style type="text/css"> <!-- .style1 { font-size: 24px; font-weight: bold; } --> </style></head><body><p>&nbsp;</p><h1 align="center">Hyrax Error - Internal Error (500)</h1><hr size="1" noshade="noshade"/><table width="100%" border="0"> <tr> <td> <img src="/opendap/docs/images/superman.jpg" alt="Bad things are happening" title="Bad things are happening" width="320" height="426"/> </td> <td> <p align="left" class="style1">OUCH!</p> <p align="left">Something Bad Happened On This Server.</p>  <p align="left">The specific error message associated with your request was:</p> <blockquote> <p><strong>BES Client Failed To Start. Message: 'Could not connect to host localhost on port 10022. Connection refused' </strong></p> </blockquote>  <p align="left">If you think that the server is broken (that the URL you submitted should have worked), then please contact the OPeNDAP user support coordinator at: <a href="mailto:support@opendap.org">support@opendap.org</a> </p> </td> </tr></table><hr size="1" noshade="noshade"/><h1 align="center">Hyrax Error - Internal Error (500)</h1></body></html>
E................
======================================================================
ERROR: runTest (tst_dap.DapTestCase)
testing access of data over http using opendap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/io/tmp_for_test/tst_dap.py", line 22, in runTest
    ncfile = netCDF4.Dataset(URL)
  File "netCDF4/_netCDF4.pyx", line 1847, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13968)
IOError: NetCDF: DAP server error
```

https://api.travis-ci.org/jobs/179546914/log.txt?deansi=true

This is new for now and 1.2.5 (cf three weeks or so ago, 1.2.4):

https://travis-ci.org/MacPython/netcdf4-python-wheels/builds/173456481

Any idea what's going on?

**Comment by jswhit** [comment]
The opendap test server is apparently down.  The travis tests NO_NET=1 to skip that test.

**Comment by jswhit** [comment]
just changed the dap server in that test to a (hopefully) more reliable one.

**Comment by matthew-brett** [comment]
Thanks - wheel tests passing with the new DAP server : https://travis-ci.org/MacPython/netcdf4-python-wheels/builds/179622820

**Pull request merged**
